//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDemoBeacon
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string DeviceName { get; set; }
        public string ZoneName { get; set; }
        public System.DateTime LogTime { get; set; }
    }
}
