#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWITRAPServices.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TwitRapDB")]
	public partial class TweetServicesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblCatLove(tblCatLove instance);
    partial void UpdatetblCatLove(tblCatLove instance);
    partial void DeletetblCatLove(tblCatLove instance);
    #endregion
		
		public TweetServicesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TwitRapDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TweetServicesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TweetServicesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TweetServicesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TweetServicesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblCatLove> tblCatLoves
		{
			get
			{
				return this.GetTable<tblCatLove>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_FetchCATLoveTweets")]
		public ISingleResult<USP_FetchCATLoveTweetsResult> USP_FetchCATLoveTweets([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fromId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fType, fromId);
			return ((ISingleResult<USP_FetchCATLoveTweetsResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCatLove")]
	public partial class tblCatLove : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private decimal _TwitID;
		
		private string _text;
		
		private System.Nullable<decimal> _userid;
		
		private string _name;
		
		private string _screenname;
		
		private string _location;
		
		private bool _IsVerified;
		
		private string _ProfileUrl;
		
		private decimal _RT_Count;
		
		private decimal _Fav_Count;
		
		private System.Nullable<System.DateTime> _created_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTwitIDChanging(decimal value);
    partial void OnTwitIDChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OnuseridChanging(System.Nullable<decimal> value);
    partial void OnuseridChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnscreennameChanging(string value);
    partial void OnscreennameChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OnIsVerifiedChanging(bool value);
    partial void OnIsVerifiedChanged();
    partial void OnProfileUrlChanging(string value);
    partial void OnProfileUrlChanged();
    partial void OnRT_CountChanging(decimal value);
    partial void OnRT_CountChanged();
    partial void OnFav_CountChanging(decimal value);
    partial void OnFav_CountChanged();
    partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_atChanged();
    #endregion
		
		public tblCatLove()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwitID", DbType="Decimal(18,0) NOT NULL")]
		public decimal TwitID
		{
			get
			{
				return this._TwitID;
			}
			set
			{
				if ((this._TwitID != value))
				{
					this.OnTwitIDChanging(value);
					this.SendPropertyChanging();
					this._TwitID = value;
					this.SendPropertyChanged("TwitID");
					this.OnTwitIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_screenname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string screenname
		{
			get
			{
				return this._screenname;
			}
			set
			{
				if ((this._screenname != value))
				{
					this.OnscreennameChanging(value);
					this.SendPropertyChanging();
					this._screenname = value;
					this.SendPropertyChanged("screenname");
					this.OnscreennameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(50)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVerified", DbType="Bit NOT NULL")]
		public bool IsVerified
		{
			get
			{
				return this._IsVerified;
			}
			set
			{
				if ((this._IsVerified != value))
				{
					this.OnIsVerifiedChanging(value);
					this.SendPropertyChanging();
					this._IsVerified = value;
					this.SendPropertyChanged("IsVerified");
					this.OnIsVerifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileUrl", DbType="NVarChar(150)")]
		public string ProfileUrl
		{
			get
			{
				return this._ProfileUrl;
			}
			set
			{
				if ((this._ProfileUrl != value))
				{
					this.OnProfileUrlChanging(value);
					this.SendPropertyChanging();
					this._ProfileUrl = value;
					this.SendPropertyChanged("ProfileUrl");
					this.OnProfileUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RT_Count", DbType="Decimal(18,0) NOT NULL")]
		public decimal RT_Count
		{
			get
			{
				return this._RT_Count;
			}
			set
			{
				if ((this._RT_Count != value))
				{
					this.OnRT_CountChanging(value);
					this.SendPropertyChanging();
					this._RT_Count = value;
					this.SendPropertyChanged("RT_Count");
					this.OnRT_CountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fav_Count", DbType="Decimal(18,0) NOT NULL")]
		public decimal Fav_Count
		{
			get
			{
				return this._Fav_Count;
			}
			set
			{
				if ((this._Fav_Count != value))
				{
					this.OnFav_CountChanging(value);
					this.SendPropertyChanging();
					this._Fav_Count = value;
					this.SendPropertyChanged("Fav_Count");
					this.OnFav_CountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class USP_FetchCATLoveTweetsResult
	{
		
		private int _Id;
		
		private decimal _TwitID;
		
		private string _text;
		
		private System.Nullable<decimal> _userid;
		
		private string _name;
		
		private string _screenname;
		
		private string _location;
		
		private bool _IsVerified;
		
		private string _ProfileUrl;
		
		private decimal _RT_Count;
		
		private decimal _Fav_Count;
		
		private System.Nullable<System.DateTime> _created_at;
		
		public USP_FetchCATLoveTweetsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwitID", DbType="Decimal(18,0) NOT NULL")]
		public decimal TwitID
		{
			get
			{
				return this._TwitID;
			}
			set
			{
				if ((this._TwitID != value))
				{
					this._TwitID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this._text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_screenname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string screenname
		{
			get
			{
				return this._screenname;
			}
			set
			{
				if ((this._screenname != value))
				{
					this._screenname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(50)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this._location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVerified", DbType="Bit NOT NULL")]
		public bool IsVerified
		{
			get
			{
				return this._IsVerified;
			}
			set
			{
				if ((this._IsVerified != value))
				{
					this._IsVerified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileUrl", DbType="NVarChar(150)")]
		public string ProfileUrl
		{
			get
			{
				return this._ProfileUrl;
			}
			set
			{
				if ((this._ProfileUrl != value))
				{
					this._ProfileUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RT_Count", DbType="Decimal(18,0) NOT NULL")]
		public decimal RT_Count
		{
			get
			{
				return this._RT_Count;
			}
			set
			{
				if ((this._RT_Count != value))
				{
					this._RT_Count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fav_Count", DbType="Decimal(18,0) NOT NULL")]
		public decimal Fav_Count
		{
			get
			{
				return this._Fav_Count;
			}
			set
			{
				if ((this._Fav_Count != value))
				{
					this._Fav_Count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this._created_at = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
